name: Selenium-docker

on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]

  jobs:
    test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@4

        - name: Install depencies maven
          run: mvn clean install


