name: Selenium-docker

on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]

jobs:
    test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Install dependencies maven
          run: mvn clean install
        - name: Run test
          run: mvn test


