name: Selenium-docker

on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]

jobs:
    test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
        - name: Install depencies maven
          run: mvn clean install
        - name: Run test
          run: mvn test


