name: Selenium-docker

on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]

jobs:
    test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          run: actions/checkout@2
        - name: Set up JDK 17
          run: actions/setup-java@1
          with:
            java-version: '17'
        - name: Install depencies maven
          run: mvn clean install
        - name: Run test
          run: mvn test


